# dro_viewer.kv à la racine du projet
#:import utils kivy.utils
#:import th_drl ui_configurator.theme_manager.draw_line

<AxisDim>:
    BoxLayout:
        orientation: "horizontal"
        spacing: 0
        padding: [0, 0,0,0]
        
        # (1) Nom de l’axe
        HoverLabel:
            id: btn_name
            text: root.name_txt
            size_hint_x: 0.3
            font_size: "20sp"
            halign: "center"
            bg_color: 1, 1, 1, 0.0
            hover_color: 0.3, 1, 0.3, 0.3
            #on_click: root.label_clicked(self)
        
        # (2) Valeur numérique (formatée texte)
        HoverLabel:
            id: btn_value
            text: root.value_txt
            size_hint_x: 0.7
            font_size: "32sp"
            halign: "right"         # alignement horizontal
            bg_color: 1, 1, 1, 0.0
            hover_color: 0.3, 1, 0.3, 0.3
            #on_release: app.open_axis_homing(root)
            #on_press: root.label_clicked(self)
        
        # (3) Bloc vertical unité / diamètre
        BoxLayout:
            id: btn_config
            orientation: "vertical"
            size_hint_x: None
            width: 50
            spacing: 0

            BoxLayout:  # LED + label diamètre
                size_hint_y: 0.5
                spacing: 2
                padding: 0
                #canvas.before:
                    #Color:
                    #    rgba: (0, 1, 0, 1) if root.val_diam else (1, 1, 1, 0.3)
                    #Ellipse:
                    #    pos: self.x + 5, self.center_y - 10
                    #    size: (14, 16)
                Label:  # diamètre
                    text: " Ø" # if root.val_diam else "r "
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                    font_size: "16sp"
                    #color: (1, 1, 1, 1) if root.val_diam else (1, 1, 1, 0.4)
                    color: (0, 1, 0, 1) if root.val_diam else (1, 1, 1, 0.3)
                    size_hint_x: 1

            MyLabel:  # unité
                text: root.val_unit
                font_size: "14sp"
                halign: "left"
                valign: "middle"

<AxisYplus>:
    BoxLayout:
        orientation: "horizontal"
        spacing: 30
        padding: [10, 5]
        
        # (1) Nom de l’axe
        HoverLabel:
            id: btn_angle
            text: "Angle"
            size_hint_x: 0.7
            font_size: "20sp"
            halign: "center"
            bg_color: 1, 1, 1, 0.0
            hover_color: 0.3, 1, 0.3, 0.3
            #on_click: root.label_clicked(self)
        
        # (2) Valeur numérique (formatée texte)
        HoverLabel:
            id: btn_valang
            text: root.angle_txt
            size_hint_x: 1
            font_size: "26sp"
            halign: "right"         # alignement horizontal
            bg_color: 1, 1, 1, 0.0
            hover_color: 0.3, 1, 0.3, 0.3
            #on_release: app.open_axis_homing(root)
            #on_press: root.label_clicked(self)


<DroHeader>:
    orientation: "horizontal"
    size_hint_y: 1
    spacing: 20
    padding: [15, 18, 15, 20]
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size

    AxisBox:    # Diamètre total (X + Y)
        id: header_vert
        axe_ident: "vert3"
    AxisBox:    # Profondeur total (Z + Y)
        id: header_hor
        axe_ident: "hor3"
    AxisBox:    # Y
        id: header_sup
        axe_ident: "s"

<DroDro>:
    orientation: "horizontal"
    spacing: 1
    size_hint_y: None
    height: dp(205)

    # Gauche : axes
    BoxLayout:
        id: dro_dim
        orientation: "vertical"
        size_hint_y: 1
        size_hint_x: 0.7
        padding: [0,0,0,dp(7)]
        spacing: 10
        canvas.before:
            Color:
                #rgba: 1, 0.1, 0.3, 0.4
                rgba: 0.12, 0.1, 0.15, 1.0
            Rectangle:
                pos: self.pos
                size: self.width, self.height

        BoxLayout:
            id: dro_axes_l1
            orientation: "horizontal"
            size_hint_x: 1
            size_hint_y: None
            height: dp(60)
            spacing: 20
            padding: [20, 5] # → marge horizontale / verticale

            AxisBox:    # X
                id: dro_x
                axe_ident: "vert"
                size_hint_x: 1
                #name_txt: "X"

            AxisBox:    # Z
                id: dro_z
                axe_ident: "hor"
                size_hint_x: 1

        BoxLayout:
            id: dro_axes_l2
            orientation: "horizontal"
            size_hint_y: None
            height: dp(58)
            size_hint_x: 1
            spacing: 0
            padding: [20, 5] # → marge horizontale / verticale

            BoxLayout:
                size_hint_y: 0.2

            AxisBox:    # Y + complément
                id: dro_y
                axe_ident: "sup"
                special: "Yplus"
                size_hint_x: 1

            BoxLayout:
                size_hint_y: 0.2


        BoxLayout:
            id: dro_axes_l3
            orientation: "horizontal"
            size_hint_y: None
            height: dp(60)
            size_hint_x: 1
            spacing: 20
            padding: [20, 5] # → marge horizontale / verticale

            AxisBox:    # S + complément
                id: dro_s
                axe_ident: "s"
                #special: "Splus"
                size_hint_x: 1

            AxisBox:    # r (complément à voir ?)
                id: dro_r
                axe_ident: "r"
                size_hint_x: 1

    # Droite : informations diverses
    BoxLayout:
        id: dro_compl
        orientation: "vertical"
        size_hint_y: 1
        #height: 300
        size_hint_x: 0.3
        canvas.before:
            Color:
                rgba: 0.1, 0.1, 0.3, 1
            Rectangle:
                pos: self.pos
                size: self.width, self.height

        Label:
            text: "Cadre d'informations logiciel (à faire)"
            font_size: "16sp"
            halign: 'center'      # Centre le texte horizontalement
            valign: 'middle'      # Centre le texte verticalement
            text_size: self.size  # 🚀 OBLIGATOIRE pour activer le multiligne !

        Label:
            text: "DRO principale"
            font_size: "20sp"
            
        Label:
            text: "🔧 Outil : P25"
        Label:
            text: "🧮 Macro : En attente"
        Label:
            text: "📝 Log : OK"

<DroGraph>:
    orientation: 'vertical' # BoxLayout principal à 1 seule case géante
    padding: 0
    spacing: 0
    size_hint: (1, 1)

    FloatLayout:
        id: zone_globale          # 🎯 ID ajouté pour l'accès Python
        size_hint: (1, 1)

        # (L'axe sera injecté ici via Python, tout en bas de la pile)

        # 🛡️ SOUS-COUCHE A : Dessins (100% de l'écran)
        StencilView:
            id: zone_decoupe
            size_hint: (1, 1)
            pos: self.parent.pos

        # 🧱 SUR-COUCHE B : Le tuteur de l'IHM
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 1)
            pos: self.parent.pos

            # 🖱️ CASE GAUCHE (75%) : Simple BoxLayout standard pour le repère de taille et la zone tactile
            BoxLayout:
                id: box_calcul_gauche
                size_hint_x: 0.85
                size_hint_y: 1
                
                #---------------------
                FloatLayout:
                    size_hint_y: None
                    height: 0

                    # Copy de box_calcul-gauche superposée (pour affichage d'info suplémentaires)
                    BoxLayout:
                        size_hint: None, None
                        size: self.parent.size
                        pos: self.parent.pos
                        padding: 2
                        orientation: 'vertical'

                        canvas.before:
                            Color:
                                rgba: 0.5, 0.2, 0.3, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        BoxLayout:
                            size_hint: 1, None
                            size: self.parent.size
                            pos: self.parent.pos
                            padding: 2
                            orientation: 'horizontal'

                            Label:
                                text: "Réf tool: "
                                halign: "center"
                                valign: "top"
                                text_size: self.size
                                font_size: "14sp"
                                color: (1, 1, 1, 0.6)
                                size_hint: None,1

                            Image:
                                source: root.offset_tool_image
                                size_hint: None, None
                                size: [dp(48),dp(48)]
                                #opacity: 1 if (root.target_screen and getattr(app, root.target_screen)["icon"]) else 0
                                allow_stretch: True

                        Widget:
                            size_hint_y: 1
            #---------------------------

            # 🎛️ CASE DROITE (25%) : Le panneau fumé
            BoxLayout:
                id: box_interface_droite
                size_hint_x: 0.15
                size_hint_y: 1
                orientation: 'vertical'
                padding: 15
                spacing: 15
                canvas.before:
                    Color:
                        rgba: 0.05, 0.05, 0.1, 0.75
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Button:
                    id: btn_fixation
                    # Si move_mode est True ➔ C'est l'usinage standard (Pièce Mobile)
                    # Si move_mode est False ➔ C'est l'inspection (Burin Mobile)
                    text: "Mode Pièce\n[ MOBILE ]" if root.move_mode else "Mode Pièce\n[ FIXE ]"
                    halign: 'center'
                    size_hint_y: None
                    height: dp(45) # Légèrement plus haut pour le multiligne au doigt
                    on_press: root.change_move_mode() # On appelle votre fonction existante !
                
                # LABEL DU NOM DE PIÈCE CAO actuellement sélectionée/dessinée
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: dp(12)
                    spacing: dp(10)  # Espace entre la fin du texte et le début de la ligne

                    Label:
                        text: "Pièce CAO:"
                        bold: False
                        font_size: '12sp'
                        size_hint_x: None
                        # Le label fait exactement la largeur de son texte
                        width: self.texture_size[0]
                        valign: 'middle'
                        text_size: None, self.height

                    Widget:
                        # Prend automatiquement 100% de la largeur restante
                        size_hint_x: 1
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex(th_drl["profil_cao"])
                            Line:
                                # self.y + self.height/2 calcule le centre vertical exact du widget
                                points: [self.x, self.y + self.height/2, self.right, self.y + self.height/2]
                                width: th_drl["profil_cao_w"]            

                Label:
                    id: cao_name_lbl
                    # On va chercher la méthode de ton PointManager stocké dans SmartDroApp
                    text: app.part.get_part_name() if hasattr(app, 'part') else "SANS NOM"
                    bold: True
                    font_size: '14sp'       # Taille normalisée pour ton panneau de droite
                    halign: 'right'
                    valign: 'top'
                    size_hint_y: None
                    height: dp(20)          # Hauteur bridée en pixels normalisés
                    text_size: self.size    # Verrouille le centrage strict de Kivy
                
                # LABEL DU NOM DE PIÈCE FAO actuellement sélectionée/dessinée
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: dp(12)
                    spacing: dp(10)  # Espace entre la fin du texte et le début de la ligne

                    Label:
                        text: "Pièce FAO:"
                        bold: False
                        font_size: '12sp'
                        size_hint_x: None
                        width: self.texture_size[0]    # Le label fait exactement la largeur de son texte
                        valign: 'middle'
                        text_size: None, self.height

                    Widget:                    
                        size_hint_x: 1    # Prend automatiquement 100% de la largeur restante
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex(th_drl["profil_fao"])
                            Line:
                                # self.y + self.height/2 calcule le centre vertical exact du widget
                                points: [self.x, self.y + self.height/2, self.right, self.y + self.height/2]
                                width: th_drl["profil_fao_w"]
                  
                Label:
                    id: part_fao_name
                    text: "Ajouter la cible"
                    bold: True
                    font_size: '14sp'       # Taille normalisée pour ton panneau de droite
                    halign: 'right'
                    valign: 'top'
                    size_hint_y: None
                    height: dp(20)          # Hauteur bridée en pixels normalisés
                    text_size: self.size    # Verrouille le centrage strict de Kivy

                # 🎯 LE RESSORT D'ATELIER (Widget élastique)
                # Il va absorber tout le vide disponible verticalement pour "plaquer" tes textes en haut
                Widget:
                    size_hint_y: 1

                Button:
                    text: "Zoom Plein"
                    halign: 'center'
                    size_hint_y: None
                    height: dp(30)          # Hauteur bridée en pixels normalisés
                    on_press: root.zoom_all_in_piece()

                Button:
                    text: "Zoom Défaut"
                    halign: 'center'
                    size_hint_y: None
                    height: dp(30)          # Hauteur bridée en pixels normalisés
                    on_press: root.zoom_def_piece()
                
                Button:
                    id: btn_recentrer
                    # Le texte change de cible selon le mode actif !
                    text: "Recentrer sur\n[ BURIN ]" if root.move_mode else "Recentrer sur\n[ PIÈCE ]"
                    halign: 'center'
                    size_hint_y: None
                    height: dp(40)
                    on_press: root.declencher_recentrage(ratio=None if root.move_mode else [0.5, 0.5])

