# cutting_tool/  cut_tool_data.kv L'usine géométrique : Calcule les points et le rayon de bec (400µm)

#:import dp kivy.metrics.dp



<LignePointGrille>:
    size_hint_y: None
    height: "35dp"
    spacing: "5dp"
    padding: ["5dp", "2dp"]

    Label:
        text: f"P{root.index}"
        size_hint_x: 0.15
        bold: True
        color: [0, 0.7, 1, 1] if root.index == 0 else [1, 1, 1, 1]

    # Champ X : Bloqué en écriture si c'est le Point 0
    TextInput:
        text: f"{root.coord_x:.1f}"
        input_filter: 'float'
        multiline: False
        readonly: root.index == 0
        background_color: [0.15, 0.15, 0.15, 1] if root.index == 0 else [0.2, 0.2, 0.2, 1]
        foreground_color: [0.5, 0.5, 0.5, 1] if root.index == 0 else [1, 1, 1, 1]
        on_text_validate: root.notifier_modification(self.text, 'x')
        on_focus: if not self.focus: root.notifier_modification(self.text, 'x')

    # Champ Y : Bloqué en écriture si c'est le Point 0
    TextInput:
        text: f"{root.coord_y:.1f}"
        input_filter: 'float'
        multiline: False
        readonly: root.index == 0
        background_color: [0.15, 0.15, 0.15, 1] if root.index == 0 else [0.2, 0.2, 0.2, 1]
        foreground_color: [0.5, 0.5, 0.5, 1] if root.index == 0 else [1, 1, 1, 1]
        on_text_validate: root.notifier_modification(self.text, 'y')
        on_focus: if not self.focus: root.notifier_modification(self.text, 'y')

    # Champ Rayon : Toujours modifiable, même pour le Point 0
    TextInput:
        text: f"{root.radius:.1f}"
        input_filter: 'float'
        multiline: False
        on_text_validate: root.notifier_modification(self.text, 'r')
        on_focus: if not self.focus: root.notifier_modification(self.text, 'r')

    # Bouton Supprimer : Masqué ou désactivé pour le Point 0
    Button:
        text: "X"
        size_hint_x: 0.15
        disabled: root.index == 0
        background_color: [0.8, 0.2, 0.2, 1] if root.index > 0 else [0.2, 0.2, 0.2, 0]
        on_release: app.root.supprimer_point(root.index)

<InsertEditor>:
    orientation: 'vertical'
    spacing: "5dp"
    padding: "5dp"

    # 1. BOX D'ENTÊTE (Données Générales)
    BoxLayout:
        size_hint_y: None
        height: "45dp"
        orientation: 'horizontal'
        spacing: "10dp"
        canvas.before:
            Color:
                rgba: [0.2, 0.2, 0.25, 1]
            Rectangle:
                pos: self.pos
                size: self.size
        
        Label:
            text: "Nom du Burin / Insert :"
            size_hint_x: None
            width: "150dp"
            bold: True
            
        TextInput:
            text: root.insert_name
            multiline: False
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            on_text: root.insert_name = self.text
            
        Label:
            text: f"Type: {root.insert_type}"
            size_hint_x: None
            width: "120dp"

        # Le ToggleButton qui pilote la visibilité de la Box 2
        ToggleButton:
            id: toggle_iso
            text: "Use Profil Normalised"
            size_hint_x: None
            width: "180dp"
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            state: "normal"

    # 2. BOX ENTÊTE_2 (Construction d'inserts normés)
    BoxLayout:
        id: normalise_profil_box
        orientation: 'vertical'
        size_hint_x: 1
        
        size_hint_y: None
        height: "45dp" if toggle_iso.state == "down" else "0dp"    # LOGIQUE DYNAMIQUE : Si enfoncé -> hauteur 45dp et visible, sinon 0dp et masqué
        opacity: 1.0 if toggle_iso.state == "down" else 0.0
        disabled: toggle_iso.state == "normal"
        spacing: "0"

        # BOX sélection de la norme
        BoxLayout:
            orientation: 'horizontal'
            spacing: "8dp"
            BoxLayout:    
                orientation: 'horizontal'  
            
            Button: 
                text: "Import géométrie"
                size_hint_x: None
                width: "180dp"
                background_color: [0.15, 0.65, 0.25, 1]

    # 3. BOX CENTRALE (Édition + Dessin)
    BoxLayout:
        orientation: 'horizontal'
        spacing: "8dp"

        # BOX GAUCHE : Formulaire d'édition de points
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.45
            canvas.before:
                Color:
                    rgba: [0.12, 0.12, 0.12, 1]
                Rectangle:
                    pos: self.pos
                    size: self.size

            # En-tête des colonnes du tableau
            BoxLayout:
                size_hint_y: None
                height: "30dp"
                padding: ["5dp", 0]
                Label:
                    text: "Point"
                    size_hint_x: 0.15
                    bold: True
                Label:
                    text: "X (µm)"
                    bold: True
                Label:
                    text: "Y (µm)"
                    bold: True
                Label:
                    text: "Rayon (µm)"
                    bold: True
                Label:
                    text: ""
                    size_hint_x: 0.15

            # Conteneur défilant pour la grille de points
            ScrollView:
                BoxLayout:
                    id: grid_points
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: "2dp"
                    padding: "2dp"

        # BOX DROITE : Zone de dessin (Canvas)
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.55
            canvas.before:
                Color:
                    rgba: [0.08, 0.08, 0.08, 1] 
                Rectangle:
                    pos: self.pos
                    size: self.size

            Widget:
                id: preview_canvas
                canvas:
                    Color:
                        rgba: [0, 0.7, 1, 1]
                    Line:
                        points: root.canvas_points
                        width: 1.5

    # 4. BOX DE VALIDATION (Pied de page)
    BoxLayout:
        size_hint_y: None
        height: "50dp"
        orientation: 'horizontal'
        spacing: "15dp"
        padding: ["10dp", "5dp"]
        
        Label:
            text: f"Vecteur Inverse Jauge : X={root.inverse_vector[0]:.1f}, Y={root.inverse_vector[1]:.1f}"
            halign: 'left'
            valign: 'middle'
            text_size: self.size

        Button:
            text: "+ Ajouter un point"
            size_hint_y: None
            height: "40dp"
            background_color: [0.2, 0.5, 0.8, 1]
            on_release: root.add_construction_point()

        Button:
            text: "- Supprimer un point"
            size_hint_y: None
            height: "40dp"
            background_color: [0.8, 0.2, 0.2, 1]
            on_release: root.del_construction_point()

        Button:
            text: "Annuler"
            size_hint_x: None
            width: "100dp"
            
        Button:
            text: "Sauvegarder l'Insert"
            size_hint_x: None
            width: "180dp"
            background_color: [0.15, 0.65, 0.25, 1]
            on_release: root.save_insert()

<CutterEditor>:
    orientation: 'vertical'
    spacing: "5dp"
    padding: "5dp"

    # 1. EN-TÊTE : NOM ET INFOS TOURELLE
    BoxLayout:
        size_hint_y: None
        height: "45dp"
        orientation: 'horizontal'
        spacing: "10dp"
        canvas.before:
            Color:
                rgba: [0.2, 0.2, 0.25, 1] if root.active_tool_ident != "199" else [0.1, 0.3, 0.1, 1] # Vert si Outil Maître
            Rectangle:
                pos: self.pos
                size: self.size
        
        Label:
            text: "Nom du Burin :" if root.active_tool_ident != "199" else "🎯 OUTIL MAÎTRE :"
            size_hint_x: None
            width: "120dp"
            bold: True
            
        TextInput:
            text: root.cutter_name
            multiline: False
            readonly: root.active_tool_ident == "199"
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            on_text: root.cutter_name = self.text

        Label:
            text: "Poste Tourelle :"
            size_hint_x: None
            width: "100dp"
        TextInput:
            text: str(root.tool_mount) if root.tool_mount is not None else ""
            input_filter: 'int'
            multiline: False
            size_hint_x: None
            width: "50dp"
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            on_text: root.tool_mount = int(self.text) if self.text else None

    # 2. SELECTION DE L'INSERT ET CONFIGURATION DU CORPS
    BoxLayout:
        size_hint_y: None
        height: "45dp"
        orientation: 'horizontal'
        spacing: "10dp"
        
        Label:
            text: "Plaquette (Insert) :"
            size_hint_x: None
            width: "130dp"
            
        Spinner:
            id: spinner_insert
            text: "Sélectionner plaquette"
            values: root.available_inserts
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            disabled: root.active_tool_ident == "199"
            on_text: root.changer_insert_associe(self.text)

        Label:
            text: "Angle Fixation (°):"
            size_hint_x: None
            width: "120dp"
        TextInput:
            text: "OLD_Mount_angle" #f"{root.mount_angle / 1000:.1f}" # Convertit les milli-degrés pour l'affichage
            input_filter: 'float'
            multiline: False
            size_hint_x: None
            width: "70dp"
            size_hint_y: None
            height: "35dp"
            pos_hint: {"center_y": 0.5}
            on_text_validate: root.modifier_angles_milli(self.text, 'mount')

    # 3. PANNEAU CENTRAL : OFFSETS TRIDIMENSIONNELS (µm) ET PREVIEW CAO
    BoxLayout:
        orientation: 'horizontal'
        spacing: "8dp"

        # Formulaire des Correcteurs à 3 Couches
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.45
            spacing: "5dp"
            canvas.before:
                Color:
                    rgba: [0.12, 0.12, 0.12, 1]
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "📋 Correcteurs de Jauge (Microns)"
                bold: True
                size_hint_y: None
                height: "30dp"

            # Grille des 3 composants Hor / Vert
            GridLayout:
                cols: 3
                spacing: "5dp"
                padding: "5dp"
                
                Label: 
                    text: "Type"
                Label: 
                    text: "Axe Horiz. (Z)"
                Label: 
                    text: "Axe Vert. (X)"

                Label: 
                    text: "1. Palpeur (Base)"
                TextInput:
                    text: str(root.offset_hor[0])
                    input_filter: 'int'
                    on_text: root.modifier_offset_couche(self.text, 'hor', 0)
                TextInput:
                    text: str(root.offset_vert[0])
                    input_filter: 'int'
                    on_text: root.modifier_offset_couche(self.text, 'vert', 0)

                Label: 
                    text: "2. Usure MCU"
                TextInput:
                    text: str(root.offset_hor[1])
                    readonly: True # Lecture seule, géré automatiquement par l'ESP32
                    background_color: [0.15, 0.15, 0.15, 1]
                TextInput:
                    text: str(root.offset_vert[1])
                    readonly: True
                    background_color: [0.15, 0.15, 0.15, 1]

                Label: 
                    text: "3. Ajustement fine"
                TextInput:
                    text: str(root.offset_hor[2])
                    input_filter: 'int'
                    on_text: root.modifier_offset_couche(self.text, 'hor', 2)
                TextInput:
                    text: str(root.offset_vert[2])
                    input_filter: 'int'
                    on_text: root.modifier_offset_couche(self.text, 'vert', 2)

        # Zone d'Affichage Graphique CAO
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.55
            canvas.before:
                Color:
                    rgba: [0.08, 0.08, 0.08, 1]
                Rectangle:
                    pos: self.pos
                    size: self.size

            Widget:
                id: preview_canvas
                canvas:
                    Color:
                        rgba: [1, 0.7, 0, 1] if root.homming_status else [0, 0.7, 1, 1] # Orange si alerte homing !
                    Line:
                        points: root.canvas_points
                        width: 1.5

    # 4. PIED DE PAGE : VALIDATION ET LOGIQUE HOMING
    BoxLayout:
        size_hint_y: None
        height: "50dp"
        orientation: 'horizontal'
        spacing: "15dp"
        padding: ["10dp", "5dp"]
        
        Label:
            text: "⚠️ Perte Réf. Tourelle/Plaquette" if root.homming_status else "✅ Burin Référencé OK"
            color: [1, 0.5, 0, 1] if root.homming_status else [0.2, 0.8, 0.2, 1]
            bold: True
            size_hint_x: 0.4
        
        Button:
            text: "Annuler"
            size_hint_x: None
            width: "100dp"
            on_release: root.annuler_modifications()
        Button:
            text: "Sauvegarder l'Outil"
            size_hint_x: None
            width: "180dp"
            background_color: [0.15, 0.65, 0.25, 1]
            on_release: root.sauvegarder_burin()


# Formulaire screen_TOOL Générales

<CutLineSelect>:
    orientation: 'horizontal'
    size_hint_y: None
    #height: dp(52)
    # 🎯 HAUTEUR DYNAMIQUE : La ligne prend la hauteur exacte demandée par son contenu textuel.
    # On ajoute dp(6) pour garder une marge (padding haut/bas) harmonieuse.
    height: self.ids.box_txt_centrale.minimum_height + dp(6) if hasattr(self, 'ids') and 'box_txt_centrale' in self.ids else dp(92)
    spacing: dp(3)
    padding: [dp(4), dp(3), dp(8), dp(3)]

    # A. LE FOND GLOBAL DE LA LIGNE (Vos 4 teintes réactives gérées par Python)
    canvas.before:
        Color:
            rgba: root.couleur_fond
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(4)]

    # B. LE BADGE DE GAUCHE : Concept de l'icône cadran sur Témoin de Sauvegarde
    BoxLayout:
        size_hint_x: None
        width: dp(54)
        size_hint_y: 1.0 # 🎯 FORCE L'ICÔNE A PRENDRE TOUTE LA HAUTEUR ADAPTATIVE
        #height: dp(52)
        padding: [dp(3), dp(3), dp(3), dp(3)]
        canvas.before:
            Color:
                # Orange éclatant si pas sauvé en RAM, sinon Gris technique d'atelier
                rgba: [0.9, 0.5, 0.0, 1] if root.non_sauve else [0.25, 0.25, 0.28, 1]
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(4)]
        Image:
            source: root.source_icone
            fit_mode: 'contain'

    # C. COLONNE CENTRALE 1 : Le Nom de l'outil & son porte-outil
    BoxLayout:
        id: box_txt_centrale
        orientation: 'vertical'
        size_hint_x: 1.0
        size_hint_y: None
        # On dit à ce bloc de mesurer sa propre hauteur en fonction des labels à l'intérieur
        height: self.minimum_height 
        spacing: dp(2)

        Label:
            text: f"id: {root.tool_ident} - {root.nom_outil}"
            bold: True
            font_size: '14sp'
            halign: 'left'
            valign: 'middle'
            # 🎯 CALCUL TEXTE AVANCÉ : On force le label à mesurer sa hauteur réelle
            # même si le texte s'étale sur 2, 3 ou 4 lignes !
            size_hint_y: None
            height: max(self.texture_size[1], dp(30))
            text_size: [self.width, None] # Largeur fixe (celle de la colonne), hauteur libre
            #text_size: self.size
            color: [0.95, 0.95, 0.98, 1]


        Label:
            text: f"{f'Porte_outil: {root.tool_mount}' if root.tool_mount is not None else 'Armoire'}"
            font_size: '12sp'
            color: [0.75, 0.75, 0.8, 1]
            halign: 'left'
            valign: 'middle'
            size_hint_y: None
            height: dp(16) # La ligne du bas reste sagement stable à 16dp
            text_size: self.size


<CutterPageHeader>:
    orientation: "horizontal"
    size_hint_y: 1.0
    padding: "0dp"
    spacing: "0dp"
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.3, 1
        Rectangle:
            pos: self.pos
            size: self.size

    # A. LE BOUTON INFO / AIDE
    BoxLayout:
        orientation: "vertical"
        size_hint_x: 0.07
        width: "40dp"
        spacing: "4dp"
        padding: "6dp"

    # B. LES INFORMATIONS TEXTUELLES (genre lignes de sélection)
    BoxLayout:
        orientation: "horizontal"
        spacing: "4dp"
        padding: ["10dp", "6dp", "8dp", "1dp"]
        size_hint_x: 0.70
    
        # 0. LE FOND GLOBAL DU CADRE OUTIL SELECTIONNÉ (Copie amélioré de <CutLineSelect>)       
        canvas.before:
            Color:
                rgba: [0.15, 0.25, 0.4, 1]      # 🔵 Bleu nuit (Outil actif dans la broche)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(4)]

        BoxLayout:      # 1. LE BADGE DE GAUCHE : Concept de l'icône cadran sur Témoin de Sauvegarde
            size_hint_x: None
            size_hint_y: 1.0 # 🎯 FORCE L'ICÔNE A PRENDRE TOUTE LA HAUTEUR ADAPTATIVE
            width: self.height
            padding: [dp(3), dp(3), dp(3), dp(3)]
            canvas.before:
                Color:
                    rgba: root.color_ico_tool
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(4)]
            Image:
                source: app.screen_CUTTER["icon"]
                fit_mode: 'contain'

        BoxLayout:      # 2. COLONNE TEXTE A DROITE : Le Nom de l'outil & son porte-outil
            id: box_txt_header
            orientation: 'vertical'
            size_hint_x: 1.0
            size_hint_y: 1.0
            spacing: dp(2)
        
            BoxLayout:      # 🟢 LIGNE 1 : LE NOM DU BURIN
                id: b_name
                orientation: "horizontal"
                spacing: "4dp"
                padding: 0
                Label:
                    text: "Burin Actif "
                    size_hint_x: 0.15
                    text_size: self.size
                    color: [0.8,0.8,0.8,0.9]
                    halign: "right"
                    valign: "middle"
                ClickableLabel:
                    text: "..."
                    size_hint_x: 0.1
                    bg_color: [0.15, 0.25, 0.4, 1]      # 🔵
                    hover_color:  [0.5,0.5,0.5,0.9]
                    halign: "center"
                    valign: "middle"
                    on_release: root.clic_editer_burin()

                ClickableLabel:
                    text: "Chargement..."
                    size_hint_x: 0.75
                    bg_color: [0.15, 0.25, 0.4, 1]      # 🔵
                    hover_color: [0.5,0.5,0.5,0.9]
                    halign: "left"
                    valign: "middle"
                    on_release: root.clic_editer_burin()

            BoxLayout:      # 🟢 LIGNE 2 : Porte-outil et insert
                id: b_tow_line
                orientation: "horizontal"
                spacing: "4dp"
                padding: 0

                Label:
                    text: "Porte-outil "
                    size_hint_x: 0.15
                    halign: "right"
                    text_size: self.size
                    color: [0.8,0.8,0.8,0.9]
                    valign: "middle"
                
                ClickableLabel:
                    text: root.manager_parent.active_tool_ident if root.ihm_initialisee else "..."
                    size_hint_x: 0.1
                    text: str(root.manager_parent.tool_mount) if (root.ihm_initialisee and root.manager_parent.tool_mount is not None) else "Aucun"
                    bg_color: [0.15, 0.25, 0.4, 1]      # 🔵
                    hover_color:  [0.5,0.5,0.5,0.9]
                    halign: "center"
                    valign: "middle"
                    on_release: 
                        if root.ihm_initialisee: root.manager_parent.on_champ_click(self, lambda txt: int(txt) if (txt.strip().isdigit()) else None, lambda val: setattr(root.manager_parent.cutter, 'tool_mount', val), "TOOL_MOUNT")

                Label:
                    text: "Insert "
                    size_hint_x: 0.15
                    halign: "right"
                    text_size: self.size
                    color: [0.8,0.8,0.8,0.9]
                    valign: "middle"
                ClickableLabel:
                    # Affichage converti de milli-degrés en degrés réels pour l'opérateur (ex: 45.0°)
                    text: f"designation insert" if root.ihm_initialisee else "-.-"
                    size_hint_x: 0.32
                    bg_color: [0.15, 0.25, 0.4, 1]      # 🔵
                    hover_color: [0.5,0.5,0.5,0.9]
                    halign: "left"
                    valign: "middle"
                    on_release: root.clic_editer_plaquette()

                Label:
                    text: "rayon"
                    size_hint_x: 0.08
                    halign: "right"
                    text_size: self.size
                    color: [0.8,0.8,0.8,0.9]
                    valign: "middle"
                ClickableLabel:
                    text: f"0.200 mm" if root.ihm_initialisee else "-.-"
                    size_hint_x: 0.2
                    bg_color: [0.15, 0.25, 0.4, 1]      # 🔵
                    hover_color: [0.5,0.5,0.5,0.9]
                    halign: "left"
                    valign: "middle"
                    on_release: root.clic_editer_plaquette()

    # C. VITESSE DE COPUPE DE L'INSERT
    BoxLayout:
        orientation: "vertical"
        size_hint_x: 0.23
        spacing: "8dp"
        padding: ["10dp", "2dp", "8dp", "1dp"]

        Label:
            text: "Vitesse de Coupe matière"
        Label:
            text: "Sélect idx vc : ....."
        Label:
            text: "Ex: acier doux ... m/min"


<CutterPageDashboard>:
    orientation: "horizontal"
    spacing: "8dp"
    padding: "8dp"

    # =====================================================================
    # ZONE GAUCHE : LE MAGASIN VIRTUEL (Sélection rapide tactile)
    # =====================================================================
    BoxLayout:
        orientation: "vertical"
        size_hint_x: 0.35
        spacing: "6dp"
        padding: "6dp"
        canvas.before:
            Color:
                rgba: 0.12, 0.12, 0.15, 1  # Fond sombre d'atelier
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            id: box_actif_tool
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height  # Dit à la box de grandir selon son contenu
            spacing: "5dp"

        Label:
            text: "Sélectionnez un outil"
            bold: True
            size_hint_y: None
            height: "35dp"
            font_size: "22sp"
            color: [0.9, 0.9, 0.95, 1]

        # 🛒 LE CONTENEUR DE DÉFILEMENT TACTILE (ScrollView)
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            bar_width: "8dp"
            bar_color: [0.3, 0.3, 0.35, 1]
            scroll_type: ['content', 'bars']  # Hyper réactif au glissement du doigt

            # La Box Verticale qui va accueillir nos lignes !
            BoxLayout:
                id: box_select_tool  # nom d'ID exclusif !
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height  # Dit à la box de grandir selon son contenu
                spacing: "5dp"

    # =====================================================================
    # ZONE DROITE : APERÇU DU BURIN SÉLECTIONNÉ ET CORRECTEURS SENSORS
    # =====================================================================

    # 3 lignes principales 1:Titre; 2: à gauche fixarions à droite offsets; 3: à gauche, en haut le manche en bas l'insert; à droite le dessin

    BoxLayout:
        orientation: "vertical"
        size_hint_x: 0.65
        spacing: "8dp"
        padding: "8dp"
        canvas.before:
            Color:
                rgba: [0.09, 0.09, 0.11, 1]
            Rectangle:
                pos: self.pos
                size: self.size
        BoxLayout:              #Ligne de titres (à voir si le header suffit pas ?)
            orientation: "horizontal"
            size_hint_y: 0.1

            Botton2ImageLed:
                id: btn_dro_ofst
                text: 'DRO_ofst'
                source_image: app.dro_visual_offset_cut[3] if root.ihm_initialisee else "bitmaps/icone.png"
                display_mode: "BOTH"    # "TEXT_ONLY" "ICON_ONLY" "BOTH"
                statut_depart: "nominal"  #"actif" "nominal_bg_claire" "nominal"
                target_screen: "sw_corp_tool"
                size_hint_y: 1
                size_hint_x: None
                width: self.height * 1.2
                on_release: root.manager_parent.ouvrir_popup_ofst_bec()
            Image:
                source: app.dro_visual_offset_cut[3] if root.ihm_initialisee else "bitmaps/icone.png"
                size_hint_x: None
                width: self.height * 1.2
            Label:
                text: "Décalage depuis le centre du bec de coupe du burin"
                size_hint_x: 0.9
                text_size: self.size
                color: [0.8,0.8,0.8,0.9]
                halign: "left"
                valign: "middle"

        BoxLayout:              #Ligne Fixation / Offsets
            orientation: "horizontal"
            size_hint_y: 0.3
            spacing: "8dp"

            BoxLayout:              # Fixation (un peux toutes les données de base)
                orientation: "vertical"
                size_hint_x: 0.5
            
                BoxLayout:    # MultiFixe
                    orientation: "vertical"
                    size_hint_x: 1
                    size_hint_y: 1
                    #width: self.height
                    padding: [dp(3), dp(3), dp(3), dp(3)]
                    canvas.before:
                        Color:
                            rgba: root.color_ofst["box_tourelle"]
                        Line:
                            rounded_rectangle: [self.x, self.y, self.width, self.height, dp(6)]
                            width: dp(1)
                    FloatLayout:
                        size_hint: (1, 0.84)

                        BoxLayout:  # Image MultiFix
                            orientation: "vertical"
                            size_hint: 0.42,1
                            pos: self.parent.pos
                            Image:
                                source: "bitmaps/W315000.png"
                                fit_mode: 'contain'
                        
                        BoxLayout:  # Data MultiFix
                            orientation: "vertical"
                            size_hint: 1.0, 1.0
                            pos: self.parent.pos

                            BoxLayout:  # TITRE: Tourelle porte-outil
                                orientation: "horizontal"
                                size_hint: 1.0, 0.6
                                Widget:
                                    size_hint_x: 0.35
                                Label:
                                    text: "Tourelle porte-outil"
                                    size_hint_x: 0.65
                                    text_size: self.size
                                    color: [0.8,0.8,0.8,0.9]
                                    bold: True
                                    halign: "center"
                                    valign: "middle"

                            BoxLayout:  # SOUS-TITRE:Offset type
                                orientation: "horizontal"
                                size_hint: 1.0, 0.6
                                Widget:
                                    size_hint_x: 0.35

                                Label:
                                    id:lbl_titre_ofst
                                    text: "Offsets type"
                                    size_hint_x: 0.65
                                    text_size: self.size
                                    color: [0.8,0.8,0.8,0.9]
                                    bold: True
                                    halign: "center"
                                    valign: "middle"
                                
                            BoxLayout:    # Angle crant MultiFix
                                orientation: "vertical"
                                size_hint_x: 1
                                canvas.before:
                                    Color:
                                        rgba: root.color_ofst["b_bg_ang_idx"]
                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [dp(4)] 
                                Label:
                                    id: lbl_tour_idx_idx
                                    text: "Index: ... Index: ... °"
                                    size_hint_x: 0.8
                                    text_size: self.size
                                    color: [0.8,0.8,0.8,0.9]
                                    halign: "right"
                                    valign: "middle"
                                Label:
                                    id: lbl_tour_idx_angle
                                    text: "Index: ... angle: ... °"
                                    size_hint_x: 0.98
                                    text_size: self.size
                                    color: [0.8,0.8,0.8,0.9]
                                    halign: "right"
                                    valign: "middle"

                            BoxLayout:    # Angle fixation tourelle-porte-outil
                                orientation: "horizontal"
                                size_hint_x: 1
                                canvas.before:
                                    Color:
                                        rgba: root.color_ofst["b_bg_ang_tour"]
                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [dp(4)]                        
                                Label:
                                    id: lbl_tour_brid
                                    text: "angle bridage: ... °"
                                    size_hint_x: 0.98
                                    text_size: self.size
                                    color: [0.8,0.8,0.8,0.9]
                                    halign: "right"
                                    valign: "middle"

                    BoxLayout:    # Angle TOTAL de la fixation
                        orientation: "horizontal"
                        size_hint_x: 1
                        size_hint_y: 0.16    
                        padding: 0
                        canvas.before:
                            Color:
                                rgba: root.color_ofst["b_bg_ang_tot"]
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(4)]        

                        ClickableLabel:
                            id: lbl_tour_tot
                            text: "... °"
                            size_hint_x: 1.0
                            #width: dp(70)
                            text_size: self.size
                            color: [0.8,0.8,0.8,0.9]
                            bg_color: [0.98, 0.18, 0.22, 0]
                            hover_color:  [0.5,0.5,0.5,0.5]
                            bold: True
                            halign: "right"
                            valign: "middle"

            BoxLayout:              # Offset (selon fixation)
                orientation: "vertical"
                size_hint_x: 0.5
                spacing: "4dp"
                padding: dp(3)
                canvas.before:
                    Color:
                        rgba: [0, 0, 0, 0] #if root.ofst_tourelle[0] else [0.8,0.5,0.5,0.6]
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(4)]
                    Color:
                        rgba: root.color_ofst["box_ofst_t"]
                    Line:
                        rounded_rectangle: [self.x, self.y, self.width, self.height, dp(6)]
                        width: dp(1)

                BoxLayout:              # entêtes colonnes
                    id: b_ofst_m
                    orientation: "horizontal"
                    size_hint_x: 1.0

                    BoxLayout:    # Alerte_rouge : Angle réf
                        orientation: "horizontal"
                        size_hint_x: 0.3
                        padding: 0
                        canvas.before:
                            Color:
                                rgba: root.color_ofst["b_bg_ref_ang"]
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(4)] 

                        Label:  # Angle de référence
                            id: lbl_ofst_a_ref
                            text: "réf: 180.00°"
                            size_hint_x: 1
                            text_size: self.size
                            color: [1,1,1,1]
                            halign: "center"
                            valign: "middle"
                    Label:  # Entête de colonne 1
                        text: "rayon"
                        size_hint_x: 0.35
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "center"
                        valign: "middle"
                    Label:  # Entête de colonne 1
                        text: "trainard"
                        size_hint_x: 0.35
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "center"
                        valign: "middle"

                BoxLayout:              # Offset Palpage
                    id: b_ofst_p
                    orientation: "horizontal"
                    size_hint_x: 1.0
                    canvas.before:
                        Color:
                            rgba: root.color_ofst["b_bg_ofst_p"]
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(4)]

                    Label:
                        text: "- lbl txt -"
                        size_hint_x: 0.3
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    ClickableLabel:
                        text: " -vert- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                            #if root.ihm_initialisee: root.manager_parent.on_champ_click(self, lambda txt: txt, lambda val: setattr(root.manager_parent.cutter, 'name', val), "TOOL_NAME")

                    ClickableLabel:
                        text: " -hor- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                BoxLayout:              # Offset Machine
                    id: b_ofst_m
                    orientation: "horizontal"
                    size_hint_x: 1.0
                    canvas.before:
                        Color:
                            rgba: root.color_ofst["b_bg_ofst_m"]
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(4)]

                    Label:
                        text: "- lbl txt -"
                        size_hint_x: 0.3
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    ClickableLabel:
                        text: " -vert- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                            #if root.ihm_initialisee: root.manager_parent.on_champ_click(self, lambda txt: txt, lambda val: setattr(root.manager_parent.cutter, 'name', val), "TOOL_NAME")

                    ClickableLabel:
                        text: " -hor- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                BoxLayout:              # Offset Mesuré (offset fin opérateur)
                    id: b_ofst_c
                    orientation: "horizontal"
                    size_hint_x: 1.0
                    canvas.before:
                        Color:
                            rgba: root.color_ofst["b_bg_ofst_c"]
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(4)]

                    Label:
                        text: "- lbl txt -"
                        size_hint_x: 0.3
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    ClickableLabel:
                        text: " -vert- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                            #if root.ihm_initialisee: root.manager_parent.on_champ_click(self, lambda txt: txt, lambda val: setattr(root.manager_parent.cutter, 'name', val), "TOOL_NAME")

                    ClickableLabel:
                        text: " -hor- "
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                BoxLayout:              # Offset TOTAL
                    id: b_ofst_t
                    orientation: "horizontal"
                    size_hint_x: 1.0
                    canvas.before:
                        Color:
                            rgba: root.color_ofst["b_bg_ofst_t"]
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(4)]

                    Label:
                        text: "- lbl txt -"
                        size_hint_x: 0.3
                        text_size: self.size
                        bold: True
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    ClickableLabel:
                        text: " -vert- "
                        bold: True
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 
                            #if root.ihm_initialisee: root.manager_parent.on_champ_click(self, lambda txt: txt, lambda val: setattr(root.manager_parent.cutter, 'name', val), "TOOL_NAME")

                    ClickableLabel:
                        text: " -hor- "
                        bold: True
                        size_hint_x: 0.35
                        hover_color:  [0.5,0.5,0.5,0.9]
                        halign: "right"
                        valign: "middle"
                        on_release: 

        BoxLayout:              #Ligne Géométrie abbrégée
            orientation: "horizontal"
            size_hint_y: 0.6
            BoxLayout:              # Dessin/image
                orientation: "vertical"
                size_hint_x: 0.5
            BoxLayout:              # Géométrie
                orientation: "vertical"
                size_hint_x: 0.5
                BoxLayout:              # Manche
                    orientation: "vertical"
                    size_hint_y: 0.5
                    
                    Label:
                        text: "Box corp d'outil"
                        size_hint_x: 1
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    #Botton2ImageLed:    # 🎛️ Mode édition du burin
                    #    text: 'Burin'
                    #    source_image: "bitmaps/burin.png"
                    #    display_mode: "BOTH"    #"ICON_ONLY"
                    #    statut_depart: "nominal"
                    #    target_screen: "sw_corp_tool"
                    #    size_hint_y: 1
                    #    size_hint_x: None
                    #    width: self.height * 1.2
                    #    on_release: root.clic_editer_burin()



                BoxLayout:              # Insert
                    orientation: "vertical"
                    size_hint_y: 0.5

                    Label:
                        text: "Insert ident ..."
                        size_hint_x: 1
                        text_size: self.size
                        color: [0.8,0.8,0.8,0.9]
                        halign: "right"
                        valign: "middle"

                    #Botton2ImageLed:    # 🎛️ Mode édition de l'insert
                    #    text: 'Insert'
                    #    source_image: "bitmaps/insert.png"
                    #    display_mode: "BOTH"
                    #    statut_depart: "nominal_warning"
                    #    target_screen: "sw_corp_tool"
                    #    size_hint_y: 1
                    #    size_hint_x: None
                    #    width: self.height * 1.2
                    #    on_release: root.clic_editer_plaquette()


