
#:import MenuButton common_widgets.MenuButton
#:import MenuButton common_widgets.BtnSwitchImageLed
#:import dp kivy.metrics.dp

# =====================================================================
# 🎛️ LA BARRE DE BOUTONS LATÉRALE UNIFIÉE (Territoire Commande)
# =====================================================================
<BaseScreenToolBar>:
    orientation: "vertical"
    size_hint_y: 1
    size_hint_x: None
    width: dp(90)
    padding: 8     
    spacing: 10     
    
    canvas.before:
        Color:
            rgba: 0.15, 0.20, 0.15, 1  
        Rectangle:
            pos: self.pos
            size: self.size

    # 🔵 Les Onglets de Navigation Pures (BottonImageLed)
    BottonImageLed:
        target_screen: "screen_FAO"
        on_release: app.changer_ecran("screen_FAO")

    BottonImageLed:
        target_screen: "screen_CAO"
        on_release: app.changer_ecran("screen_CAO")

    BottonImageLed:
        target_screen: "screen_OFFSET"
        on_release: app.changer_ecran("screen_OFFSET")

    BottonImageLed:
        target_screen: "screen_CUTTER"
        on_release: app.changer_ecran("screen_CUTTER")

    BottonImageLed:
        target_screen: "screen_MCU"
        on_release: app.changer_ecran("screen_MCU")

    SwitchImageLed:    # 🎛️ L'Interrupteur Permanent Machine (SwitchImageLed)
        target_screen: "sw_TACTILE"
        size_hint_y: 0.7
        on_release: app.basculer_mode_tactile()

    BottonImageLed:
        target_screen: "screen_PARAM"
        size_hint_y: 0.7
        on_release: app.changer_ecran("screen_PARAM")

    BottonImageLed:
        target_screen: "screen_SETTING"
        size_hint_y: 0.7
        on_release: app.changer_ecran("screen_SETTING")


# =====================================================================
# 🖥️ 2. LE GABARIT CHÂSSIS UNIVERSEL POUR TOUTES LES PAGES
# =====================================================================
#<BaseScreenLayout>:
<BaseMenuScreen>:
    size_hint_x: 1
    size_hint_y: 1
    orientation: 'vertical'
    spacing: 0
    padding: 0


    # 1️⃣ L'ENTÊTE HAUTE (Bandeau d'infos indispensables)
    BoxLayout:
        id: header_zone   
        size_hint_y: None
        height: dp(70)
        canvas.before:
            Color:
                rgba: 0.1, 0.1, 0.15, 1
            Rectangle:
                pos: self.pos
                size: self.size

    # 🧱 LE CORPS INFÉRIEUR (Barre à gauche, contenu à droite)
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 1
        spacing: 0
        padding: 0

        # 2️⃣ LA BARRE DE BOUTONS LATÉRALE (Toujours visible à gauche)
        BaseScreenToolBar:
            id: tools_bar    # 🎯 VALIDÉ : C'est notre barre d'outils

        # 3️⃣ LA ZONE DE CONTENU PRINCIPALE (À droite)
        BoxLayout:
            id: body_zone     # 🎯 VALIDÉ : C'est le corps de nos formulaires
            size_hint_x: 1
            size_hint_y: 1
            orientation: 'vertical'
            spacing: 0
            padding: 0


<FullTactileScreenLayout>:
    orientation: 'vertical'
    spacing: 0
    padding: 0

    # 1️⃣ La box àdisposition pour insérer votre page
    BoxLayout:
        id: box_zone   
        size_hint_x: 1
        size_hint_y: 1
        orientation: 'vertical'
        spacing: 0
        padding: 0


    FloatLayout:
        size_hint_y: None
        height: 0

        # 🟦 Le conteneur du cadre (C'est lui qui gère la taille et la position absolue)
        BoxLayout:
            id: float_input_box
            size_hint: None, None
            size: 0, 0        # 💡 Un poil plus grand (100 + 2px de bordure de chaque côté)
            pos: -2, 500         # Position sur l'écran
            padding: 2            # 🎯 L'épaisseur de votre cadre bleu !
            orientation: 'vertical'

            # 🎨 Dessin du cadre bleu en arrière-plan
            canvas.before:
                Color:
                    rgba: [0.2, 0.6, 0.9, 1] # Bleu
                Rectangle:
                    pos: self.pos
                    size: self.size

            # 🎯 L'Input Text (Il prend 100% de la place restante après le padding)
            TextInput:
                id: input_text_floating
                size_hint: 1, 1   # ✅ Parfait ! Il s'adapte au BoxLayout
                multiline: False
                cursor_color: [0.2, 0.6, 0.9, 1]
                background_color: [0.18, 0.18, 0.22, 1]
                foreground_color: [0.95, 0.95, 1, 1]
                disabled: True
                
                on_text_validate: root.save_floating_input()
                on_focus: if not self.focus: root.save_floating_input()
