# machine_tool/ machine_data.kv

#:import dp kivy.metrics.dp

<McuPageHeader>:
    orientation: "horizontal"
    size_hint_y: 1.0
    padding: ["15dp", "4dp", "8dp", "4dp"]
    canvas.before:
        Color:
            rgba: 0.15, 0.15, 0.18, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "💪 DIAGNOSTIC ET ENTRÉES/SORTIES DU MATÉRIEL"
        bold: True
        font_size: "14sp"
        halign: "left"
        text_size: self.size
        valign: "middle"

<McuPageDashboard>:
    canvas.before:
        Color:
            rgba: 0.08, 0.08, 0.1, 1
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "🚧 Statut matériel et monitoring du thread ESP32-S3 en cours de construction..."
        font_size: "15sp"
        color: [0.9, 0.5, 0.0, 1]
        halign: "center"